### ISSUE TITLE
Unreliable letter capitalization over remote desktop connection

### ISSUE THREAD

**Issue by apptent-studios** [TabbycatPie/CustomKeyboard#19]
Hi,

I created a macro writing "AbCd" and "AbCdEfG" (with delay after strokes).

I tried to use them over a Microsoft Terminal Server connection/remote desktop over slower connection. There was on open Notepad to type in, but the result is random. Letters are OK but not all capitals are capital.

Generally there is no such issue when I type by hand.

I attach the printout and the config file too. Thank you in advance if this could be handled or any workarounds are welcome.
[20240109.txt](https://github.com/TabbycatPie/CustomKeyboard/files/13877414/20240109.txt)
![20240109](https://github.com/TabbycatPie/CustomKeyboard/assets/10520189/25693351-8661-4dbe-a5a9-4d2cf2494648)

**Comment by TabbycatPie** [comment]
Thx for ur comment. Can you show me the software interface where you set your macros? This product does not work very well on remote connections. If adjusting the delay does not help in your situation, it may be because the interval between the key press and key release is too short (and it is fixed in my firmware). Sorry for the inconvenience.
